### ISSUE TITLE
Database Not working for Docker container

### ISSUE THREAD

**Issue by jmcgrath207** [afourmy/eNMS#120]
I am getting this issues when I try to run the docker container. This issue is only when I pull from master, However it works for git tag 3.6v

```bash
Attaching to enms_db_1, enms_enms_1, enms_nginx_1
db_1     | The files belonging to this database system will be owned by user "postgres".
db_1     | This user must also own the server process.
db_1     | 
db_1     | The database cluster will be initialized with locale "en_US.utf8".
db_1     | The default database encoding has accordingly been set to "UTF8".
db_1     | The default text search configuration will be set to "english".
db_1     | 
db_1     | Data page checksums are disabled.
db_1     | 
db_1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1     | creating subdirectories ... ok
db_1     | selecting default max_connections ... 100
db_1     | selecting default shared_buffers ... 128MB
db_1     | selecting dynamic shared memory implementation ... posix
db_1     | creating configuration files ... ok
db_1     | running bootstrap script ... ok
enms_1   | [2019-01-22 03:29:02 +0000] [1] [DEBUG] Current configuration:
enms_1   |   config: gunicorn.py
enms_1   |   bind: ['0.0.0.0:5000']
enms_1   |   backlog: 2048
enms_1   |   workers: 5
enms_1   |   worker_class: sync
enms_1   |   threads: 1
enms_1   |   worker_connections: 1000
enms_1   |   max_requests: 0
enms_1   |   max_requests_jitter: 0
enms_1   |   timeout: 1000
enms_1   |   graceful_timeout: 1000
enms_1   |   keepalive: 2
enms_1   |   limit_request_line: 4094
enms_1   |   limit_request_fields: 100
enms_1   |   limit_request_field_size: 8190
enms_1   |   reload: False
enms_1   |   reload_engine: auto
enms_1   |   reload_extra_files: []
enms_1   |   spew: False
enms_1   |   check_config: False
enms_1   |   preload_app: False
enms_1   |   sendfile: None
enms_1   |   reuse_port: False
enms_1   |   chdir: /
enms_1   |   daemon: False
enms_1   |   raw_env: []
enms_1   |   pidfile: None
enms_1   |   worker_tmp_dir: None
enms_1   |   user: 0
enms_1   |   group: 0
enms_1   |   umask: 0
enms_1   |   initgroups: False
enms_1   |   tmp_upload_dir: None
enms_1   |   secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
enms_1   |   forwarded_allow_ips: ['127.0.0.1']
enms_1   |   accesslog: -
enms_1   |   disable_redirect_access_to_syslog: False
enms_1   |   access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
enms_1   |   errorlog: -
enms_1   |   loglevel: debug
enms_1   |   capture_output: True
enms_1   |   logger_class: gunicorn.glogging.Logger
enms_1   |   logconfig: None
enms_1   |   logconfig_dict: {}
enms_1   |   syslog_addr: udp://localhost:514
enms_1   |   syslog: False
enms_1   |   syslog_prefix: None
enms_1   |   syslog_facility: user
enms_1   |   enable_stdio_inheritance: True
enms_1   |   statsd_host: None
enms_1   |   statsd_prefix: 
enms_1   |   proc_name: None
enms_1   |   default_proc_name: app:app
enms_1   |   pythonpath: None
enms_1   |   paste: None
enms_1   |   on_starting: <function OnStarting.on_starting at 0x7f7f6285c2f0>
enms_1   |   on_reload: <function OnReload.on_reload at 0x7f7f6285c400>
enms_1   |   when_ready: <function WhenReady.when_ready at 0x7f7f6285c510>
enms_1   |   pre_fork: <function Prefork.pre_fork at 0x7f7f6285c620>
enms_1   |   post_fork: <function Postfork.post_fork at 0x7f7f6285c730>
enms_1   |   post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f7f6285c840>
enms_1   |   worker_int: <function WorkerInt.worker_int at 0x7f7f6285c950>
enms_1   |   worker_abort: <function WorkerAbort.worker_abort at 0x7f7f6285ca60>
enms_1   |   pre_exec: <function PreExec.pre_exec at 0x7f7f6285cb70>
enms_1   |   pre_request: <function PreRequest.pre_request at 0x7f7f6285cc80>
enms_1   |   post_request: <function PostRequest.post_request at 0x7f7f6285cd08>
enms_1   |   child_exit: <function ChildExit.child_exit at 0x7f7f6285ce18>
enms_1   |   worker_exit: <function WorkerExit.worker_exit at 0x7f7f6285cf28>
enms_1   |   nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f7f628760d0>
enms_1   |   on_exit: <function OnExit.on_exit at 0x7f7f628761e0>
enms_1   |   proxy_protocol: False
enms_1   |   proxy_allow_ips: ['127.0.0.1']
enms_1   |   keyfile: None
enms_1   |   certfile: None
enms_1   |   ssl_version: 2
enms_1   |   cert_reqs: 0
enms_1   |   ca_certs: None
enms_1   |   suppress_ragged_eofs: True
enms_1   |   do_handshake_on_connect: False
enms_1   |   ciphers: TLSv1
enms_1   |   raw_paste_global_conf: []
enms_1   | [2019-01-22 03:29:02 +0000] [1] [INFO] Starting gunicorn 19.9.0
enms_1   | [2019-01-22 03:29:02 +0000] [1] [DEBUG] Arbiter booted
enms_1   | [2019-01-22 03:29:02 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
enms_1   | [2019-01-22 03:29:02 +0000] [1] [INFO] Using worker: sync
enms_1   | [2019-01-22 03:29:02 +0000] [8] [INFO] Booting worker with pid: 8
enms_1   | [2019-01-22 03:29:02 +0000] [9] [INFO] Booting worker with pid: 9
enms_1   | [2019-01-22 03:29:02 +0000] [10] [INFO] Booting worker with pid: 10
enms_1   | [2019-01-22 03:29:02 +0000] [11] [INFO] Booting worker with pid: 11
enms_1   | [2019-01-22 03:29:02 +0000] [15] [INFO] Booting worker with pid: 15
enms_1   | [2019-01-22 03:29:02 +0000] [1] [DEBUG] 5 workers
nginx_1  | 2019/01/22 03:29:02 [warn] 1#1: conflicting server name "" on 0.0.0.0:80, ignored
nginx_1  | nginx: [warn] conflicting server name "" on 0.0.0.0:80, ignored
db_1     | performing post-bootstrap initialization ... ok
db_1     | syncing data to disk ... ok
db_1     | 
db_1     | WARNING: enabling "trust" authentication for local connections
db_1     | You can change this by editing pg_hba.conf or using the option -A, or
db_1     | --auth-local and --auth-host, the next time you run initdb.
db_1     | 
db_1     | Success. You can now start the database server using:
db_1     | 
db_1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1     | 
db_1     | waiting for server to start....2019-01-22 03:29:03.154 UTC [43] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1     | 2019-01-22 03:29:03.205 UTC [44] LOG:  database system was shut down at 2019-01-22 03:29:02 UTC
db_1     | 2019-01-22 03:29:03.227 UTC [43] LOG:  database system is ready to accept connections
db_1     |  done
db_1     | server started
db_1     | CREATE DATABASE
db_1     | 
db_1     | 
db_1     | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1     | 
db_1     | 2019-01-22 03:29:03.746 UTC [43] LOG:  received fast shutdown request
db_1     | waiting for server to shut down....2019-01-22 03:29:03.750 UTC [43] LOG:  aborting any active transactions
db_1     | 2019-01-22 03:29:03.753 UTC [43] LOG:  background worker "logical replication launcher" (PID 50) exited with exit code 1
db_1     | 2019-01-22 03:29:03.753 UTC [45] LOG:  shutting down
db_1     | 2019-01-22 03:29:03.791 UTC [43] LOG:  database system is shut down
db_1     |  done
db_1     | server stopped
db_1     | 
db_1     | PostgreSQL init process complete; ready for start up.
db_1     | 
db_1     | 2019-01-22 03:29:03.871 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1     | 2019-01-22 03:29:03.871 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1     | 2019-01-22 03:29:03.880 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1     | 2019-01-22 03:29:03.913 UTC [61] LOG:  database system was shut down at 2019-01-22 03:29:03 UTC
db_1     | 2019-01-22 03:29:03.927 UTC [1] LOG:  database system is ready to accept connections
enms_1   | 01-22-2019 03:29:04 INFO     eNMS starting
enms_1   | 01-22-2019 03:29:04 INFO     eNMS starting
enms_1   | 01-22-2019 03:29:04 INFO     eNMS starting
enms_1   | 01-22-2019 03:29:04 INFO     eNMS starting
enms_1   | 01-22-2019 03:29:04 INFO     eNMS starting
enms_1   | [2019-01-22 03:30:00 +0000] [10] [DEBUG] GET /
db_1     | 2019-01-22 03:30:01.413 UTC [68] ERROR:  operator does not exist: character varying = bigint at character 337
db_1     | 2019-01-22 03:30:01.413 UTC [68] HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
db_1     | 2019-01-22 03:30:01.413 UTC [68] STATEMENT:  SELECT "Instance".id AS "Instance_id", "Instance".name AS "Instance_name", "Instance".description AS "Instance_description", "Instance".ip_address AS "Instance_ip_address", "Instance".weight AS "Instance_weight", "Instance".status AS "Instance_status", "Instance".cpu_load AS "Instance_cpu_load" 
db_1     | 	FROM "Instance" 
db_1     | 	WHERE "Instance".name = 2485378351107 
db_1     | 	 LIMIT 1
enms_1   | /usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
enms_1   |   """)
enms_1   | 01-22-2019 03:30:01 ERROR    Exception on / [GET]
enms_1   | Traceback (most recent call last):
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1230, in _execute_context
enms_1   |     cursor, statement, parameters, context
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 536, in do_execute
enms_1   |     cursor.execute(statement, parameters)
enms_1   | psycopg2.ProgrammingError: operator does not exist: character varying = bigint
enms_1   | LINE 3: WHERE "Instance".name = 2485378351107 
enms_1   |                               ^
enms_1   | HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
enms_1   | 
enms_1   | 
enms_1   | The above exception was the direct cause of the following exception:
enms_1   | 
enms_1   | Traceback (most recent call last):
enms_1   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
enms_1   |     response = self.full_dispatch_request()
enms_1   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1808, in full_dispatch_request
enms_1   |     self.try_trigger_before_first_request_functions()
enms_1   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1855, in try_trigger_before_first_request_functions
enms_1   |     func()
enms_1   |   File "/eNMS/__init__.py", line 78, in initialize_database
enms_1   |     configure_instance_id()
enms_1   |   File "/eNMS/admin/helpers.py", line 16, in configure_instance_id
enms_1   |     'status': 'Up'
enms_1   |   File "/eNMS/base/helpers.py", line 80, in factory
enms_1   |     instance = fetch(cls_name, name=kwargs['name'])
enms_1   |   File "/eNMS/base/helpers.py", line 22, in fetch
enms_1   |     return db.session.query(classes[model]).filter_by(**kwargs).first()
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3010, in first
enms_1   |     ret = list(self[0:1])
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2800, in __getitem__
enms_1   |     return list(res)
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3112, in __iter__
enms_1   |     return self._execute_and_instances(context)
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3137, in _execute_and_instances
enms_1   |     result = conn.execute(querycontext.statement, self._params)
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 974, in execute
enms_1   |     return meth(self, multiparams, params)
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 273, in _execute_on_connection
enms_1   |     return connection._execute_clauseelement(self, multiparams, params)
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1093, in _execute_clauseelement
enms_1   |     distilled_params,
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1234, in _execute_context
enms_1   |     e, statement, parameters, cursor, context
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1452, in _handle_dbapi_exception
enms_1   |     util.raise_from_cause(sqlalchemy_exception, exc_info)
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
enms_1   |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 276, in reraise
enms_1   |     raise value.with_traceback(tb)
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1230, in _execute_context
enms_1   |     cursor, statement, parameters, context
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 536, in do_execute
enms_1   |     cursor.execute(statement, parameters)
enms_1   | sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) operator does not exist: character varying = bigint
enms_1   | LINE 3: WHERE "Instance".name = 2485378351107 
enms_1   |                               ^
enms_1   | HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
enms_1   |  [SQL: 'SELECT "Instance".id AS "Instance_id", "Instance".name AS "Instance_name", "Instance".description AS "Instance_description", "Instance".ip_address AS "Instance_ip_address", "Instance".weight AS "Instance_weight", "Instance".status AS "Instance_status", "Instance".cpu_load AS "Instance_cpu_load" \nFROM "Instance" \nWHERE "Instance".name = %(name_1)s \n LIMIT %(param_1)s'] [parameters: {'name_1': 2485378351107, 'param_1': 1}] (Background on this error at: http://sqlalche.me/e/f405)
enms_1   | 172.24.0.1 - - [22/Jan/2019:03:30:01 +0000] "GET / HTTP/1.1" 500 291 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
enms_1   | [2019-01-22 03:30:02 +0000] [9] [DEBUG] GET /favicon.ico
db_1     | 2019-01-22 03:30:03.235 UTC [69] ERROR:  operator does not exist: character varying = bigint at character 337
db_1     | 2019-01-22 03:30:03.235 UTC [69] HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
db_1     | 2019-01-22 03:30:03.235 UTC [69] STATEMENT:  SELECT "Instance".id AS "Instance_id", "Instance".name AS "Instance_name", "Instance".description AS "Instance_description", "Instance".ip_address AS "Instance_ip_address", "Instance".weight AS "Instance_weight", "Instance".status AS "Instance_status", "Instance".cpu_load AS "Instance_cpu_load" 
db_1     | 	FROM "Instance" 
db_1     | 	WHERE "Instance".name = 2485378351107 
db_1     | 	 LIMIT 1
enms_1   | /usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
enms_1   |   """)
enms_1   | 01-22-2019 03:30:03 ERROR    Exception on /favicon.ico [GET]
enms_1   | Traceback (most recent call last):
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1230, in _execute_context
enms_1   |     cursor, statement, parameters, context
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 536, in do_execute
enms_1   |     cursor.execute(statement, parameters)
enms_1   | psycopg2.ProgrammingError: operator does not exist: character varying = bigint
enms_1   | LINE 3: WHERE "Instance".name = 2485378351107 
enms_1   |                               ^
enms_1   | HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
enms_1   | 
enms_1   | 
enms_1   | The above exception was the direct cause of the following exception:
enms_1   | 
enms_1   | Traceback (most recent call last):
enms_1   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
enms_1   |     response = self.full_dispatch_request()
enms_1   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1808, in full_dispatch_request
enms_1   |     self.try_trigger_before_first_request_functions()
enms_1   |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1855, in try_trigger_before_first_request_functions
enms_1   |     func()
enms_1   |   File "/eNMS/__init__.py", line 78, in initialize_database
enms_1   |     configure_instance_id()
enms_1   |   File "/eNMS/admin/helpers.py", line 16, in configure_instance_id
enms_1   |     'status': 'Up'
enms_1   |   File "/eNMS/base/helpers.py", line 80, in factory
enms_1   |     instance = fetch(cls_name, name=kwargs['name'])
enms_1   |   File "/eNMS/base/helpers.py", line 22, in fetch
enms_1   |     return db.session.query(classes[model]).filter_by(**kwargs).first()
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3010, in first
enms_1   |     ret = list(self[0:1])
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2800, in __getitem__
enms_1   |     return list(res)
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3112, in __iter__
enms_1   |     return self._execute_and_instances(context)
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3137, in _execute_and_instances
enms_1   |     result = conn.execute(querycontext.statement, self._params)
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 974, in execute
enms_1   |     return meth(self, multiparams, params)
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 273, in _execute_on_connection
enms_1   |     return connection._execute_clauseelement(self, multiparams, params)
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1093, in _execute_clauseelement
enms_1   |     distilled_params,
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1234, in _execute_context
enms_1   |     e, statement, parameters, cursor, context
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1452, in _handle_dbapi_exception
enms_1   |     util.raise_from_cause(sqlalchemy_exception, exc_info)
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
enms_1   |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 276, in reraise
enms_1   |     raise value.with_traceback(tb)
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1230, in _execute_context
enms_1   |     cursor, statement, parameters, context
enms_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 536, in do_execute
enms_1   |     cursor.execute(statement, parameters)
enms_1   | sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) operator does not exist: character varying = bigint
enms_1   | LINE 3: WHERE "Instance".name = 2485378351107 
enms_1   |                               ^
enms_1   | HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
enms_1   |  [SQL: 'SELECT "Instance".id AS "Instance_id", "Instance".name AS "Instance_name", "Instance".description AS "Instance_description", "Instance".ip_address AS "Instance_ip_address", "Instance".weight AS "Instance_weight", "Instance".status AS "Instance_status", "Instance".cpu_load AS "Instance_cpu_load" \nFROM "Instance" \nWHERE "Instance".name = %(name_1)s \n LIMIT %(param_1)s'] [parameters: {'name_1': 2485378351107, 'param_1': 1}] (Background on this error at: http://sqlalche.me/e/f405)
enms_1   | 172.24.0.1 - - [22/Jan/2019:03:30:03 +0000] "GET /favicon.ico HTTP/1.1" 500 291 "http://0.0.0.0:5000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
```

**Comment by afourmy** [comment]
I think I fixed it. I will close the issue for now, but you can reopen if you still encounter this bug.
Thanks !
