### ISSUE TITLE
Installation problem Gunicorn Python 3.5

### ISSUE THREAD

**Issue by mcmyst** [afourmy/eNMS#136]
Hi,

I have followed the installation documentation here:
https://enms.readthedocs.io/en/latest/base/installation.html

I have seen that eNMS requires Python3.6 or erlier, so that I have installed python3.7:

```
root@enms:~/eNMS# ls -l /usr/local/bin/python3.7
-rwxr-xr-x 2 root staff 14420336 mai    8 23:46 /usr/local/bin/python3.7
```

When I start gunicorn, I have an error:

```
[2019-05-09 15:57:52 +0200] [15998] [INFO] Starting gunicorn 19.9.0
[2019-05-09 15:57:52 +0200] [15998] [DEBUG] Arbiter booted
[2019-05-09 15:57:52 +0200] [15998] [INFO] Listening at: http://0.0.0.0:5000 (15998)
[2019-05-09 15:57:52 +0200] [15998] [INFO] Using worker: sync
[2019-05-09 15:57:52 +0200] [16001] [INFO] Booting worker with pid: 16001
[2019-05-09 15:57:52 +0200] [16001] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/root/eNMS/app.py", line 5, in <module>
    from eNMS import create_app
  File "/root/eNMS/eNMS/__init__.py", line 67
    module = import_module(f"eNMS.{blueprint}")
                                             ^
SyntaxError: invalid syntax
[2019-05-09 15:57:52 +0200] [16001] [INFO] Worker exiting (pid: 16001)
[2019-05-09 15:57:52 +0200] [15998] [DEBUG] 1 workers
[2019-05-09 15:57:52 +0200] [15998] [INFO] Shutting down: Master
[2019-05-09 15:57:52 +0200] [15998] [INFO] Reason: Worker failed to boot.
```

I see in the error log that gunicorn is using python3.5 insted of python3.7.

Do you have an idea how to switch on python3.7 ?

Thank you

**Comment by afourmy** [comment]
Hello,

I don't know, I suggest you have a look at gunicorn docs.
This is unrelated to eNMS so I'll close.

**Comment by mcmyst** [comment]
@afourmy , myabe the problem is not in eNMS but I literally followed the documentation on a fresh install of Debian 9.0. Maybe the problem is on the install documentation here : 

https://enms.readthedocs.io/en/latest/base/installation.html

Thank you
