### ISSUE TITLE
Using External Postgres DB with docker container

### ISSUE THREAD

**Issue by robp2175** [afourmy/eNMS#137]
I would like to use this in Production in a docker container using an external postgres dabatase server. I tried placing all of the environements variables in .env for the postgres server. I also tried placing them in .env-pgsql. I also modified dcoker-compose.yml file because I dont need the db or nginx (I already have an nginx container). Unfortunately, the schema is not found/created. I do already have an enms database with enms user and password with privileges on my postgres server ready to go. If this won't work, then I have no issue spinning up another box to run this, but I would love to just be able to use it in a container. Thanks for any assistance with this. This is a great looking project and I am excited to give it a go. 

```
ENMS_SECRET_KEY=docker
ENMS_CONFIG_MODE=production
USE_VAULT=1
POSTGRES_USER=enms
POSTGRES_PASSWORD=password
POSTGRES_DB=enms
POSTGRES_HOST=emlnx-mysql1.domain.edu
POSTGRES_PORT=5432
```

```
version: "3"
services:
  enms:
    restart: always
    env_file: .env
    build: .
    ports:
      - "5000:5000"

```

```
enms_1  | [2019-05-16 11:28:03 +0000] [1] [DEBUG] 1 workers
enms_1  | [2019-05-16 11:28:07 +0000] [8] [ERROR] Exception in worker process
enms_1  | Traceback (most recent call last):
enms_1  |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
enms_1  |     worker.init_process()
enms_1  |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
enms_1  |     self.load_wsgi()
enms_1  |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
enms_1  |     self.wsgi = self.app.wsgi()
enms_1  |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
enms_1  |     self.callable = self.load()
enms_1  |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
enms_1  |     return self.load_wsgiapp()
enms_1  |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
enms_1  |     return util.import_app(self.app_uri)
enms_1  |   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
enms_1  |     __import__(module)
enms_1  |   File "/app.py", line 15, in <module>
enms_1  |     app = create_app(Path.cwd(), config_mode)
enms_1  |   File "/eNMS/__init__.py", line 210, in create_app
enms_1  |     configure_vault_client(app)
enms_1  |   File "/eNMS/__init__.py", line 84, in configure_vault_client
enms_1  |     if vault_client.sys.is_sealed() and app.config["UNSEAL_VAULT"]:
enms_1  |   File "/usr/local/lib/python3.6/site-packages/hvac/api/system_backend/seal.py", line 12, in is_sealed
enms_1  |     seal_status = self.read_seal_status()
enms_1  |   File "/usr/local/lib/python3.6/site-packages/hvac/api/system_backend/seal.py", line 28, in read_seal_status
enms_1  |     url=api_path,
enms_1  |   File "/usr/local/lib/python3.6/site-packages/hvac/adapters.py", line 93, in get
enms_1  |     return self.request('get', url, **kwargs)
enms_1  |   File "/usr/local/lib/python3.6/site-packages/hvac/adapters.py", line 267, in request
enms_1  |     **_kwargs
enms_1  |   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
enms_1  |     prep = self.prepare_request(req)
enms_1  |   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
enms_1  |     hooks=merge_hooks(request.hooks, self.hooks),
enms_1  |   File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
enms_1  |     self.prepare_url(url, params)
enms_1  |   File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
enms_1  |     raise MissingSchema(error)
enms_1  | requests.exceptions.MissingSchema: Invalid URL 'None/v1/sys/seal-status': No schema supplied. Perhaps you meant http://None/v1/sys/seal-status?
enms_1  | [2019-05-16 11:28:07 +0000] [8] [INFO] Worker exiting (pid: 8)
enms_1  | [2019-05-16 11:28:07 +0000] [1] [INFO] Shutting down: Master
enms_1  | [2019-05-16 11:28:07 +0000] [1] [INFO] Reason: Worker failed to boot.
```

**Comment by afourmy** [comment]
As you can see from the stacktrace, this is not a database but a Vault issue. You don't have a working Vault in your environment, yet the `USE_VAULT` variable is set to 1 so eNMS is looking for a Vault to store/fetch passwords.
Try setting `USE_VAULT=0`, or adding a Vault to your docker-compose setup.

**Comment by robp2175** [comment]
Thank you, I misread read the issue. I appreciate it. I have hit another issue, but I'll open another thread.
