### ISSUE TITLE
Postgres error type modifier is not allowed for type "text" device_name TEXT(65536)

### ISSUE THREAD

**Issue by robp2175** [afourmy/eNMS#138]
I am using postgres 11. The tables appear to have been created correctly after first startup. Thank you.

```
enms_1  | 05-16-2019 11:51:57 ERROR    Exception on /favicon.ico [GET]
enms_1  | Traceback (most recent call last):
enms_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
enms_1  |     cursor, statement, parameters, context
enms_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
enms_1  |     cursor.execute(statement, parameters)
enms_1  | psycopg2.errors.SyntaxError: type modifier is not allowed for type "text"
enms_1  | LINE 4:  device_name TEXT(65536),
enms_1  |                      ^


enms_1  | The above exception was the direct cause of the following exception:
enms_1  |
enms_1  | Traceback (most recent call last):
enms_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
enms_1  |     response = self.full_dispatch_request()
enms_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1808, in full_dispatch_request
enms_1  |     self.try_trigger_before_first_request_functions()
enms_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1855, in try_trigger_before_first_request_functions
enms_1  |     func()
enms_1  |   File "/eNMS/__init__.py", line 105, in initialize_database
enms_1  |     db.create_all()
enms_1  |   File "/usr/local/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 1033, in create_all
enms_1  |     self._execute_for_all_tables(app, bind, 'create_all')
enms_1  |   File "/usr/local/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 1025, in _execute_for_all_tables
enms_1  |     op(bind=self.get_engine(app, bind), **extra)
enms_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 4287, in create_all
enms_1  |     ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
enms_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2033, in _run_visitor
enms_1  |     conn._run_visitor(visitorcallable, element, **kwargs)
enms_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1607, in _run_visitor
enms_1  |     visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
enms_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 131, in traverse_single
enms_1  |     return meth(obj, **kw)
enms_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 781, in visit_metadata
enms_1  |     _is_metadata_operation=True,
enms_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 131, in traverse_single
enms_1  |     return meth(obj, **kw)
enms_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 826, in visit_table
enms_1  |     include_foreign_key_constraints,
enms_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
enms_1  |     return meth(self, multiparams, params)
enms_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
enms_1  |     return connection._execute_ddl(self, multiparams, params)
enms_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1050, in _execute_ddl
enms_1  |     compiled,
enms_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
enms_1  |     e, statement, parameters, cursor, context
enms_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
enms_1  |     util.raise_from_cause(sqlalchemy_exception, exc_info)
enms_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
enms_1  |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
enms_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
enms_1  |     raise value.with_traceback(tb)
enms_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
enms_1  |     cursor, statement, parameters, context
enms_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
enms_1  |     cursor.execute(statement, parameters)
enms_1  | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) type modifier is not allowed for type "text"
enms_1  | LINE 4:  device_name TEXT(65536),


```

**Comment by afourmy** [comment]
Looks like Text doesn't accept a length argument with PostgreSQL: https://stackoverflow.com/questions/8671418/rails-3-heroku-pgerror-error-type-modifier-is-not-allowed-for-type-text
I am testing eNMS with SQLite and MySQL so I haven't seen this.

The solution for now would be to remove the argument for all Text fields manually.
`s/Text(DB_STRING_LENGTH)/Text`

**Comment by robp2175** [comment]
Is MySQL an option? If yes, I have a MySQL server and could just use that, but I don’t see any documentation on that option.

**Comment by afourmy** [comment]
Yes MySQL is an option, but the docs is not yet up-to-date.
There are my notes regarding MySQL, perhaps you can reuse some of that

```
sudo apt install -y mysql-server python3-mysqldb
sudo mysql
CREATE USER 'enms'@'localhost' IDENTIFIED BY 'enms';
GRANT ALL PRIVILEGES ON *.* TO 'enms'@'localhost' WITH GRANT OPTION;
export ENMS_DATABASE_URL=mysql://enms:enms@localhost/mysql
```

**Comment by robp2175** [comment]
I had to add mysqlclient to the requirements.txt file and rebuild the image, but then it worked perfect. Thank You, can’t wait to try it out.

**Comment by dBitech** [comment]
> Looks like Text doesn't accept a length argument with PostgreSQL: https://stackoverflow.com/questions/8671418/rails-3-heroku-pgerror-error-type-modifier-is-not-allowed-for-type-text
> I am testing eNMS with SQLite and MySQL so I haven't seen this.
> 
> The solution for now would be to remove the argument for all Text fields manually.
> `s/Text(DB_STRING_LENGTH)/Text`

Correct TEXT is of unlimited length.  if you wish to have a uperbound set for the length of the filed use VARCHAR instead of TEXT

**Comment by afourmy** [comment]
Okay thanks :) It's not really that I wish to have an upperbound, we added one only because it turns out MySQL fails if there is no upperbound.
Looks like that change is not compatible with PostgreSQL.
I will add a database detection mechanism upon eNMS initialization so that an upperbound is used or not, depending on the type of database.

**Comment by robp2175** [comment]
Switching to a MySQL database worked great for me.  Thank you for the help.
