### ISSUE TITLE
eNMS doesn't start after fresh install

### ISSUE THREAD

**Issue by Geertkok1** [afourmy/eNMS#168]
After a fresh install on Ubuntu 18.04.3 eNMS doenst start but instead give's the following error if I start it with flask:
```
flask run --host=0.0.0.0
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployme                                                                                                                                                             nt.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/beheerder/.local/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/home/beheerder/.local/lib/python2.7/site-packages/flask/cli.py", line 9                                                                                                                                                             66, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "/home/beheerder/.local/lib/python2.7/site-packages/flask/cli.py", line 5                                                                                                                                                             86, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/beheerder/.local/lib/python2.7/site-packages/click/core.py", line                                                                                                                                                              717, in main
    rv = self.invoke(ctx)
  File "/home/beheerder/.local/lib/python2.7/site-packages/click/core.py", line                                                                                                                                                              1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/beheerder/.local/lib/python2.7/site-packages/click/core.py", line                                                                                                                                                              956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/beheerder/.local/lib/python2.7/site-packages/click/core.py", line                                                                                                                                                              555, in invoke
    return callback(*args, **kwargs)
  File "/home/beheerder/.local/lib/python2.7/site-packages/click/decorators.py",                                                                                                                                                              line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/beheerder/.local/lib/python2.7/site-packages/click/core.py", line                                                                                                                                                              555, in invoke
    return callback(*args, **kwargs)
  File "/home/beheerder/.local/lib/python2.7/site-packages/flask/cli.py", line 8                                                                                                                                                             48, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/home/beheerder/.local/lib/python2.7/site-packages/flask/cli.py", line 3                                                                                                                                                             05, in __init__
    self._load_unlocked()
  File "/home/beheerder/.local/lib/python2.7/site-packages/flask/cli.py", line 3                                                                                                                                                             30, in _load_unlocked
    self._app = rv = self.loader()
  File "/home/beheerder/.local/lib/python2.7/site-packages/flask/cli.py", line 3                                                                                                                                                             92, in load_app
    app = locate_app(self, import_name, None, raise_if_not_found=False)
  File "/home/beheerder/.local/lib/python2.7/site-packages/flask/cli.py", line 2                                                                                                                                                             40, in locate_app
    __import__(module_name)
  File "/home/beheerder/eNMS/app.py", line 1, in <module>
    from eNMS.framework import create_app
  File "/home/beheerder/eNMS/eNMS/__init__.py", line 1, in <module>
    from eNMS.controller import App
  File "/home/beheerder/eNMS/eNMS/controller/__init__.py", line 1, in <module>
    from eNMS.controller.administration import AdministrationController
  File "/home/beheerder/eNMS/eNMS/controller/administration.py", line 31
    user=f"{self.config['ldap']['userdn']}\\{name}",
                                                  ^
SyntaxError: invalid syntax
```
and the following error if i run it with gunicorn:

```
gunicorn --config gunicorn.py app:app
[2019-12-09 10:57:43 +0000] [2239] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  accesslog: -
  disable_redirect_access_to_syslog: False
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7fc8386700c8>
  errorlog: -
  enable_stdio_inheritance: True
  worker_class: sync
  ssl_version: 2
  suppress_ragged_eofs: True
  syslog_facility: user
  when_ready: <function when_ready at 0x7fc8386e1e60>
  pre_fork: <function pre_fork at 0x7fc8386e1f50>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  sendfile: None
  reuse_port: False
  group: 1000
  umask: 0
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  workers: 1
  graceful_timeout: 3000
  do_handshake_on_connect: False
  spew: False
  proc_name: None
  pre_exec: <function pre_exec at 0x7fc838670488>
  worker_tmp_dir: None
  strip_header_spaces: False
  limit_request_fields: 100
  pythonpath: None
  on_exit: <function on_exit at 0x7fc8386709b0>
  logconfig: None
  logconfig_dict: {}
  config: gunicorn.py
  pidfile: None
  check_config: False
  statsd_prefix:
  on_reload: <function on_reload at 0x7fc8386e1d70>
  reload_engine: auto
  reload_extra_files: []
  user: 1000
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7fc838670578>
  post_request: <function post_request at 0x7fc8386705f0>
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7fc8386702a8>
  chdir: /home/beheerder/eNMS
  daemon: False
  paste: None
  raw_paste_global_conf: []
  threads: 1
  max_requests: 0
  limit_request_line: 0
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  on_starting: <function on_starting at 0x7fc8386e1c80>
  post_worker_init: <function post_worker_init at 0x7fc8386701b8>
  worker_abort: <function worker_abort at 0x7fc838670398>
  worker_exit: <function worker_exit at 0x7fc8386707d0>
  default_proc_name: app:app
  loglevel: debug
  capture_output: True
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  ciphers: TLSv1
  syslog: False
  bind: ['0.0.0.0:5000']
  raw_env: []
  initgroups: False
  reload: False
  limit_request_field_size: 8190
  child_exit: <function child_exit at 0x7fc8386706e0>
  nworkers_changed: <function nworkers_changed at 0x7fc8386708c0>
  timeout: 3000
  keyfile: None
  ca_certs: None
  tmp_upload_dir: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
[2019-12-09 10:57:43 +0000] [2239] [INFO] Starting gunicorn 19.10.0
[2019-12-09 10:57:43 +0000] [2239] [DEBUG] Arbiter booted
[2019-12-09 10:57:43 +0000] [2239] [INFO] Listening at: http://0.0.0.0:5000 (2239)
[2019-12-09 10:57:43 +0000] [2239] [INFO] Using worker: sync
[2019-12-09 10:57:43 +0000] [2243] [INFO] Booting worker with pid: 2243
[2019-12-09 10:57:43 +0000] [2243] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/beheerder/.local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 586, in spawn_worker
    worker.init_process()
  File "/home/beheerder/.local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/beheerder/.local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/beheerder/.local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/beheerder/.local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/beheerder/.local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/beheerder/.local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/beheerder/eNMS/app.py", line 1, in <module>
    from eNMS.framework import create_app
  File "/home/beheerder/eNMS/eNMS/__init__.py", line 1, in <module>
    from eNMS.controller import App
  File "/home/beheerder/eNMS/eNMS/controller/__init__.py", line 1, in <module>
    from eNMS.controller.administration import AdministrationController
  File "/home/beheerder/eNMS/eNMS/controller/administration.py", line 31
    user=f"{self.config['ldap']['userdn']}\\{name}",
                                                  ^
SyntaxError: invalid syntax
[2019-12-09 10:57:43 +0000] [2243] [INFO] Worker exiting (pid: 2243)
[2019-12-09 10:57:43 +0000] [2239] [DEBUG] 1 workers
[2019-12-09 10:57:43 +0000] [2239] [INFO] Shutting down: Master
[2019-12-09 10:57:43 +0000] [2239] [INFO] Reason: Worker failed to boot.
```

I installed eNMS following the guide on the wiki.
Is this a know issue or did I do something wrong?

**Comment by afourmy** [comment]
py3.6+ only

**Comment by Geertkok1** [comment]
I can confirm that is was because of an old python version. It seems the install guide on [the wiki](https://enms.readthedocs.io/en/latest/base/installation.html) is outdated since in mentions installing using pip instead of pip3

**Comment by afourmy** [comment]
No it's not. The docs explicitly mentions py3.6 here: https://enms.readthedocs.io/en/latest/base/installation.html#installation
whether "pip" refers to python2 or 3 depends on your environment
