### ISSUE TITLE
Scheduler Unreacheable

### ISSUE THREAD

**Issue by Jacobog3** [afourmy/eNMS#363]
innova@eNMS:/opt/eNMS$ gunicorn --config gunicorn.py scheduler:scheduler
[2021-09-06 18:47:29 +0000] [3369581] [DEBUG] Current configuration:
  config: gunicorn.py
  wsgi_app: None
  bind: ['0.0.0.0:5000']
  backlog: 2048
  workers: 1
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 3000
  graceful_timeout: 3000
  keepalive: 2
  limit_request_line: 0
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: True
  sendfile: None
  reuse_port: False
  chdir: /opt/eNMS
  daemon: False
  raw_env: ['TERM=screen']
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: -
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: -
  loglevel: debug
  capture_output: True
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: True
  statsd_host: None
  dogstatsd_tags:
  statsd_prefix:
  proc_name: None
  default_proc_name: scheduler:scheduler
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7fea047f24c0>
  on_reload: <function OnReload.on_reload at 0x7fea047f25e0>
  when_ready: <function WhenReady.when_ready at 0x7fea047f2700>
  pre_fork: <function Prefork.pre_fork at 0x7fea047f2820>
  post_fork: <function post_fork at 0x7fea047f61f0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7fea047f2a60>
  worker_int: <function WorkerInt.worker_int at 0x7fea047f2b80>
  worker_abort: <function WorkerAbort.worker_abort at 0x7fea047f2ca0>
  pre_exec: <function PreExec.pre_exec at 0x7fea047f2dc0>
  pre_request: <function PreRequest.pre_request at 0x7fea047f2ee0>
  post_request: <function PostRequest.post_request at 0x7fea047f2f70>
  child_exit: <function ChildExit.child_exit at 0x7fea048090d0>
  worker_exit: <function WorkerExit.worker_exit at 0x7fea048091f0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7fea04809310>
  on_exit: <function OnExit.on_exit at 0x7fea04809430>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 118, in setup
    self.app.wsgi()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/innova/.local/lib/python3.8/site-packages/scheduler/__init__.py", line 10, in <module>
    from scheduler.core import Scheduler
  File "/home/innova/.local/lib/python3.8/site-packages/scheduler/core.py", line 14, in <module>
    from scheduler.job import (
  File "/home/innova/.local/lib/python3.8/site-packages/scheduler/job.py", line 31, in <module>
    _TimingCyclicList = list[TimingCyclic]
TypeError: 'type' object is not subscriptable

**Comment by afourmy** [comment]
this code from the stacktrace doesn't come from eNMS. I don't know what "Scheduler" this is, but it's not the right one.
