### ISSUE TITLE
Update README for Python 3.7

### ISSUE THREAD

**Issue by sph0lt0n** [afourmy/eNMS#383]
In README.md, section Quick Install, we find:

> Install python 3.6+ (earlier versions not supported)

Attempts to install under Python 3.6 fail with the following traceback:

```
Collecting argon2-cffi-bindings (from argon2-cffi->-r
build/requirements/requirements.txt (line 2))
  Downloading
https://files.pythonhosted.org/packages/b9/e9/184b8ccce6683b0aa2fbb7ba5683ea4b9c5763f1356347f1312c32e3c66e/argon2-cffi-bindings-21.2.0.tar.gz
(1.8MB)
    100% |████████████████████████████████| 1.8MB 1.1MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-f4qbe8xk/argon2-cffi-bindings/setup.py", line 111, in <module>
        cffi_modules=CFFI_MODULES,
      File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 370, in __init__
        k: v for k, v in attrs.items()
      File "/usr/lib64/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 529, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
        return self.resolve()
      File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/tmp/pip-build-f4qbe8xk/argon2-cffi-bindings/.eggs/setuptools_scm-7.0.4-py3.6.egg/setuptools_scm/__init__.py", line 5
        from __future__ import annotations
        ^
    SyntaxError: future feature annotations is not defined

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in
/tmp/pip-build-f4qbe8xk/argon2-cffi-bindings/

SyntaxError: future feature annotations is not defined
```

Apparently, recent updates to **argon2** now require **annotations**, unavailable until Python 3.7

As an alternative to back porting annotations to Python 3.6, I'd suggest updating the README.md statement of intended support to Python 3.7

**Comment by afourmy** [comment]
updated readme + docs to 3.7, thanks
