### ISSUE TITLE
Flask fails to start on fresh install

### ISSUE THREAD

**Issue by nathantmoss** [afourmy/eNMS#391]
Running command: "flask run --host 0.0.0.0"

Output:

flask run --host=0.0.0.0
Traceback (most recent call last):
  File "/home/nate/.local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/nate/.local/lib/python3.10/site-packages/flask/cli.py", line 1047, in main
    cli.main()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/nate/.local/lib/python3.10/site-packages/flask/cli.py", line 911, in run_command
    raise e from None
  File "/home/nate/.local/lib/python3.10/site-packages/flask/cli.py", line 897, in run_command
    app = info.load_app()
  File "/home/nate/.local/lib/python3.10/site-packages/flask/cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "/home/nate/.local/lib/python3.10/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/home/nate/eNMS/app.py", line 1, in <module>
    from eNMS.server import server as app  # noqa: F401
  File "/home/nate/eNMS/eNMS/__init__.py", line 1, in <module>
    from eNMS.controller import controller
  File "/home/nate/eNMS/eNMS/controller.py", line 34, in <module>
    from eNMS.database import db
  File "/home/nate/eNMS/eNMS/database.py", line 42, in <module>
    from eNMS.variables import vs
  File "/home/nate/eNMS/eNMS/variables.py", line 5, in <module>
    from napalm._SUPPORTED_DRIVERS import SUPPORTED_DRIVERS
  File "/home/nate/.local/lib/python3.10/site-packages/napalm/__init__.py", line 11, in <module>
    import napalm.iosxr
  File "/home/nate/.local/lib/python3.10/site-packages/napalm/iosxr/__init__.py", line 27, in <module>
    __version__ = pkg_resources.get_distribution("napalm-iosxr").version
  File "/home/nate/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 514, in get_distribution
    dist = get_provider(dist)
  File "/home/nate/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 386, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/home/nate/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 956, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/nate/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 815, in resolve
    dist = self._resolve_dist(
  File "/home/nate/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 844, in _resolve_dist
    env = Environment(self.entries)
  File "/home/nate/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1044, in __init__
    self.scan(search_path)
  File "/home/nate/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1077, in scan
    self.add(dist)
  File "/home/nate/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1096, in add
    dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
  File "/home/nate/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2631, in hashcmp
    self.parsed_version,
  File "/home/nate/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2678, in parsed_version
    self._parsed_version = parse_version(self.version)
  File "/home/nate/.local/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/version.py", line 266, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '1.1build1'

**Comment by nathantmoss** [comment]
Maybe a python version issue?

**Comment by nathantmoss** [comment]
Issue was resolved by downgrading pip. 

command: pip install --upgrade --user setuptools==58.3.0
