### ISSUE TITLE
TypeError with flask-wtf v1.1

### ISSUE THREAD

**Issue by d-k-7** [afourmy/eNMS#392]
The following exception is raised whenever a form is submitted:
```
/update/ansible_playbook_service (500)
Traceback (most recent call last):
  File "/projects/enms/eNMS/eNMS/server.py", line 153, in decorated_function
    result = function(*args, **kwargs)
  File "/projects/enms/eNMS/eNMS/server.py", line 366, in route
    if not form.validate_on_submit():
  File "/projects/enms/lib/python3.9/site-packages/flask_wtf/form.py", line 86,
in validate_on_submit
    return self.is_submitted() and self.validate(extra_validators=extra_validators)
TypeError: validate() got an unexpected keyword argument 'extra_validators'
```

workaround I used:
`pip3 install flask_wtf==v1.0.1` after installing requirements.txt

**Comment by SaneiSaya** [comment]
Thank you for this. I was having issue creating new services and workflows and this was the fix.
