### ISSUE TITLE
error during login.

### ISSUE THREAD

**Issue by amanjazari** [afourmy/eNMS#49]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/html/project/eNMS/source/admin/routes.py", line 63, in login
    if user and cisco_type7.verify(password, user.password):
  File "/usr/local/lib/python2.7/dist-packages/passlib/utils/handlers.py", line 757, in verify
    self = cls.from_string(hash, **context)
  File "/usr/local/lib/python2.7/dist-packages/passlib/handlers/cisco.py", line 366, in from_string
    salt = int(hash[:2]) # may throw ValueError
ValueError: invalid literal for int() with base 10: 'am'

**Comment by afourmy** [comment]
Hello @amanjazari ,

I guess it happened after changing the password of an existing user from the admin panel.
If so, it is fixed. If I'm wrong and it happens again, feel free to reopen this issue.

Thank you for the feedback
