### ISSUE TITLE
builtins.SyntaxError : import_module()

### ISSUE THREAD

**Issue by dBitech** [afourmy/eNMS#95]
Followig error when accessing http://localhost:5000

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/opt/eNMS/app.py", line 7, in <module>
    from eNMS import create_app, db
File "/opt/eNMS/eNMS/__init__.py", line 59
    module = import_module(f'eNMS.{blueprint}')
                                             ^
SyntaxError: invalid syntax
```

Flask 1.02
Python 3.5.3

**Comment by afourmy** [comment]
py3.6+ only as per readme/docs
